spring.application.name=discussion
server.port=24130

# Liquibase
spring.liquibase.enabled=false
spring.liquibase.url=jdbc:cassandra://localhost:9042/distcomp?compliancemode=Liquibase&localdatacenter=datacenter1
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver

# DataSource
spring.datasource.name=cassandra_datasource
spring.datasource.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver
spring.datasource.url=jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1

# Database configuration
spring.cassandra.keyspace-name=distcomp
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.port=9042
spring.cassandra.request.timeout=5s

# Logging
logging.level.com.javarush.discussion.reaction=DEBUG