spring.application.name=ReactFlow
server.port=24110

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Migration with Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml

logging.charset.console=utf-8
logging.level.com.javarush.publisher.controller=DEBUG
logging.level.com.javarush.publisher.service=DEBUG
logging.level.org.springframework.security.authentication=DEBUG

# Security. App authentication
jwt.secret=some-secret
jwt.expiration=900000
cookie.name.token=access_token

# Security. Google
spring.security.oauth2.client.registration.google.client-id=1061819671424-abrtf4ib1pfcme4i0mhu6lllllqo9og8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:24110/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# Security. Keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8443/realms/keycloak-auth
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.client-id=distcomp-keycloak-client
spring.security.oauth2.client.registration.keycloak.client-secret=uewcCuya9Fnr8W7rcWtjewmCy5HuIV6g
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:24110/login/oauth2/keycloak
