spring.application.name=ReactFlow
server.port=24110

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Migration with Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml

logging.charset.console=utf-8
logging.level.com.javarush.reactflow.controller=DEBUG
logging.level.com.javarush.reactflow.service=DEBUG
